name: Job Alerts

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  run-job-alerts:
    runs-on: ubuntu-latest
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      ACTIONS_STEP_DEBUG: true  # Enable debug logging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests urllib3 beautifulsoup4
      - name: Verify environment variables
        run: |
          echo "Checking environment variables..."
          echo "EMAIL_USER: ${EMAIL_USER:-'Not set'}"
          echo "EMAIL_PASS: ${EMAIL_PASS:-'Not set'}"
          echo "EMAIL_RECEIVER: ${EMAIL_RECEIVER:-'Not set'}"
          if [ -z "$EMAIL_USER" ]; then
            echo "Error: EMAIL_USER is missing"
            exit 1
          fi
          if [ -z "$EMAIL_PASS" ]; then
            echo "Error: EMAIL_PASS is missing"
            exit 1
          fi
          if [ -z "$EMAIL_RECEIVER" ]; then
            echo "Error: EMAIL_RECEIVER is missing"
            exit 1
          fi
          echo "All environment variables are set"
      - name: Run script
        run: python scripts/job_alerts.py
