name: Job Alerts

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  run-job-alerts:
    runs-on: ubuntu-latest
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      ACTIONS_STEP_DEBUG: true  # Enable debug logging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests urllib3 beautifulsoup4
      - name: Verify environment variables
        run: |
          echo "EMAIL_USER: $EMAIL_USER"
          echo "EMAIL_RECEIVER: $EMAIL_RECEIVER"
          if [ -z "$EMAIL_USER" ] || [ -z "$EMAIL_PASS" ] || [ -z "$EMAIL_RECEIVER" ]; then
            echo "Error: One or more environment variables are missing"
            exit 1
          fi
      - name: Run script
        run: python scripts/job_alerts.py
